(function(){
const money=n=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(n);
const checker=document.getElementById('rafChecker');
if(checker){let step=1;const total=8;const qs=[...checker.querySelectorAll('.question')];const next=document.getElementById('nextBtn'),back=document.getElementById('backBtn'),finish=document.getElementById('finishBtn'),bar=document.getElementById('progressBar'),label=document.getElementById('stepLabel');
function show(){qs.forEach(q=>q.hidden=+q.dataset.step!==step);back.hidden=step===1;next.hidden=step===total;finish.hidden=step!==total;bar.style.width=(step/total*100)+'%';label.textContent=`Question ${step} of ${total}`}
function valid(){const q=qs[step-1];const controls=q.querySelectorAll('input,select');return [...controls].some(c=>c.required&&((c.type==='radio'&&c.checked)||(!['radio','checkbox'].includes(c.type)&&c.value)))}
next.onclick=()=>{if(!valid()){alert('Please answer this question before continuing.');return}step++;show()};back.onclick=()=>{step--;show()};checker.onsubmit=e=>{e.preventDefault();if(!valid())return;const fd=new FormData(checker);const result=document.getElementById('result');const title=document.getElementById('resultTitle'),text=document.getElementById('resultText'),list=document.getElementById('resultList');let items=[];if(fd.get('accident')==='no'||fd.get('injury')==='no'){title.textContent='A consultation may still be useful';text.textContent='Your answers do not establish the usual injury/death scenario assessed by this screening tool. A practitioner can explain whether another legal route may be relevant.'}else{title.textContent='Your circumstances may warrant an RAF consultation';text.textContent='Your answers contain factors commonly relevant to an RAF claim. They do not establish liability, seriousness, prescription, quantum or the prospects of success.';items=['Obtain and keep hospital, medical and clinical records.','Keep accident/police reports, witness details and photographs where available.','Keep proof of earnings and documents showing time away from work or reduced earning capacity.','Ask about applicable time limits and whether any prescribed forms or reports are required.'];if(fd.get('docs')==='no')items.unshift('Start gathering supporting documents before the consultation.');if(fd.get('lodged')==='yes')items.push('Bring the claim number and all correspondence or offers received from the RAF.')}list.innerHTML=items.map(x=>`<li>${x}</li>`).join('');result.hidden=false;result.scrollIntoView({behavior:'smooth'});};show();}
const calc=document.getElementById('rafCalc');if(calc){calc.onsubmit=e=>{e.preventDefault();const income=+document.getElementById('incomeInput').value,months=+document.getElementById('monthsInput').value,reduction=+document.getElementById('reductionInput').value/100,years=+document.getElementById('yearsInput').value;const past=income*months,future=income*12*years*reduction,total=past+future;document.getElementById('calcTotal').textContent=money(total);document.getElementById('calcBreakdown').innerHTML=`<div><span>Illustrative past loss</span><strong>${money(past)}</strong></div><div><span>Illustrative future loss</span><strong>${money(future)}</strong></div><div><span>Combined simple estimate</span><strong>${money(total)}</strong></div>`;document.getElementById('calcResult').hidden=false;document.getElementById('calcResult').scrollIntoView({behavior:'smooth'});}}
})();
